### ISSUE TITLE
Package it up to homebrew

### ISSUE THREAD

**Issue by vanniktech** [m1foley/fit-commit#15]
Is there any plan on providing it on homebrew or should Mac users just use gem?

**Comment by m1foley** [comment]
OS X comes with Ruby pre-installed, so it should be easy to use `gem` per the install instructions. However, I'll look into this later to see if adding it to `brew` will make install even easier. I'm a OS X user who's fine using `gem` for installations, but I might be in the minority there.

**Comment by m1foley** [comment]
Closing because:
- Packaging with Homebrew doesn't make things easier for users, while adding more maintenance work and potentially more bugs. 
- [pre-commit](https://github.com/jish/pre-commit) doesn't have Homebrew support either.

OS X is mentioned specifically in the instructions, so it should be clear how to install on OS X.
