### ISSUE TITLE
Verb pedantry

### ISSUE THREAD

**Issue by noahfrederick** [m1foley/fit-commit#6]
> Message must use present imperative tense.

Imperative describes a verb's mood, not its tense (present is its tense). However, I propose that what you're referring to is actually a bare infinitive (both have the same form, different functions). The commit message is not commanding someone to make a change—it serves as a description of the change already made—so I propose that something like "Fix bug #1111" is a noun phrase headed by an infinitive rather than being a finite clause.

Thoughts?

Proposed language:

> Message must use an infinitive.

**Comment by m1foley** [comment]
Thanks for the correction.

I should have written "imperative present tense" -- that's the technically correct term, and how commit messages are commonly described. It does use a bare infinitive, but I think "imperative present tense" is more precise ("this can fix a bug" also contains a bare infinitive) and easier to understand.

"Imperative" is appropriate because the official [Git documentation](http://git.kernel.org/cgit/git/git.git/tree/Documentation/SubmittingPatches?id=HEAD) states:

> Describe your changes in imperative mood, e.g. "make xyzzy do frotz" instead of "[This patch] makes xyzzy do frotz" or "[I] changed xyzzy to do frotz", as if you are giving orders to the codebase to change its behaviour.

I will also add an example to the README for clarity. Does all this sound reasonable to you?

**Comment by noahfrederick** [comment]
Sure, that sounds reasonable. I wasn't aware that the Git docs explicitly recommend the imperative. I think it's odd, but I agree that saying "imperative" is easier to understand in any case. Thanks for humoring me.
